name: Build OpenClash .run (APK)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Directories
        run: mkdir -p openclash-x86 openclash-aarch64

      - name: Checkout OpenClash package branch
        uses: actions/checkout@v4
        with:
          repository: vernesong/OpenClash
          ref: package
          path: OpenClash-Package

      - name: Checkout OpenClash core branch
        uses: actions/checkout@v4
        with:
          repository: vernesong/OpenClash
          ref: core
          path: OpenClash-Core

      - name: Prepare Files
        run: |
          # 复制 apk 到工作目录
          cp OpenClash-Package/master/*.apk openclash-x86/
          cp OpenClash-Package/master/*.apk openclash-aarch64/

          # 获取版本号
          VERSION=$(head -n 1 OpenClash-Package/master/version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # 解压 x86_64 核心
          tar -xzvf OpenClash-Core/master/meta/clash-linux-amd64-v1.tar.gz -C openclash-x86/
          mv openclash-x86/clash openclash-x86/clash_meta

          # 解压 aarch64 核心
          tar -xzvf OpenClash-Core/master/meta/clash-linux-arm64.tar.gz -C openclash-aarch64/
          mv openclash-aarch64/clash openclash-aarch64/clash_meta

      - name: Create install.sh
        run: |
          cat << 'EOF' > openclash-x86/install.sh
          #!/bin/sh
          apk add --allow-untrusted --force-overwrite --clean-protected *.apk
          mkdir -p /etc/openclash/core
          mv clash_meta /etc/openclash/core/
          chmod +x /etc/openclash/core/clash_meta
          echo "安装完成。"
          EOF
          chmod +x openclash-x86/install.sh
          cp openclash-x86/install.sh openclash-aarch64/install.sh

      - name: Create .run packages
        run: |
          git clone https://github.com/megastep/makeself.git
          ./makeself/makeself.sh openclash-x86/ OpenClash_x86_64_${{ env.VERSION }}.run "OpenClash by Actions" ./install.sh
          ./makeself/makeself.sh openclash-aarch64/ OpenClash_aarch64_${{ env.VERSION }}.run "OpenClash by Actions" ./install.sh

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: openclash-${{ env.VERSION }}
          name: "OpenClash ${{ env.VERSION }}"
          files: OpenClash_*.run
